### ISSUE TITLE
ARM version only?

### ISSUE THREAD

**Issue by AmnaSN** [macstadium/orka-desktop#8]
Does orka-desktop only have ARM version? or is it also for intel?

**Comment by abojak** [comment]
Hello Amna.
We officially support Apple ARM chips (M1-M3) with Orka Desktop. There are
no current plans to support x86 with our free virtualization application.
Orka Cluster (orchestrated CI/CD cloud) does run apple HVF on Intel nodes.
Regards.
Andrew Bojak
MacStadium
Orka PM

**Comment by AmnaSN** [comment]
Thanks for the clarification
